# mode: ruby
# vi: set ft=ruby :

# máy host
Vagrant.configure("2") do |config|
    config.vm.box="centos/7"
    config.vm.network "private_network", ip:"192.168.10.100"
    config.vm.hostname="master.xtl"

    # máy ảo được tạo ra có: (tối thiểu 2 nhân và 2gb ram)
    config.vm.provider "virtualbox" do |vb|
        vb.name="master.xtl"
        vb.cpus=2
        vb.memory="2048"
    end
    
    # chạy shell sau khi nạp box
    config.vm.provision "shell",path:"./../install-docker-kube.sh"
    config.vm.provision "shell", inline: <<-SHELL
        # root: 123 cho phép ssh
        echo "123" | passwd --stdin root
        sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
        systemctl reload sshd

cat >>/etc/hosts<<EOF
192.168.10.100 master.xtl
192.168.10.101 worker1.xtl
192.168.10.102 worker2.xtl
EOF

    SHELL
end