Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2004"
    config.vm.box_version = "3.6.8"
    config.vm.hostname = "virtualbox-guest-vm"
    config.vm.network "private_network", ip: "172.16.16.16"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "virtualbox-guest-vm"
        vb.memory = 1024
        vb.cpus = 1
    end

    config.vm.provision "shell" do |s|
        # ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
        s.inline = <<-SHELL
            echo "123" | passwd --stdin root
            sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
            systemctl reload sshd
        SHELL
    end
end